baseURL = 'https://himsafar-ebon.vercel.app/'
languageCode = 'en-us'
title = 'Himsafar'
theme = "ananke"

[params]
  featured_image = '/images/722_0451.JPG'
  mainSections = ["posts"]

[params.ananke]
  show_recent_posts = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 11
